import {
  draftToPipelineConfig,
  pipelineConfigToRequestedStages,
  type PipelineSelectionDraft,
} from '@lib/pipelineConfig'
import type { ProcessBatchStatus, ProcessStageStatus } from 'types/pipelineContracts'

const processPipelineDraft: PipelineSelectionDraft = {
  profileId: 'custom',
  mode: 'custom',
  steps: {
    ingester: true,
    normalizePass1: {
      enabled: true,
      advancedOpen: false,
      subSelection: {
        split: true,
        rotate: true,
      },
    },
    normalizePass2: {
      enabled: true,
      advancedOpen: false,
      subSelection: {
        split: true,
        rotate: true,
      },
    },
    ocrProcessor: true,
    contentDedup: true,
    metadataExtraction: true,
    metadataValidation: true,
    rightsDeterminator: true,
    fedoraIngester: false,
  },
}

/*
 * Keep this fixture generated by the same builder used by process-documents.
 * The services receive this execution-plan shape from the dashboard.
 */
export const processPipelineConfig = draftToPipelineConfig(processPipelineDraft)
const processPipelineRequestedStages = pipelineConfigToRequestedStages(processPipelineConfig)

export function createProcessStage(overrides: Partial<ProcessStageStatus> = {}): ProcessStageStatus {
  return {
    status: 'pending',
    requestId: 'request-1',
    requestedByApp: 'preserv-dashboard',
    initiatedAt: null,
    startedAt: null,
    completedAt: null,
    lastTransitionAt: null,
    error: null,
    callbackDeliveryStatus: null,
    callbackNotifiedAt: null,
    callbackReceivedAt: null,
    callbackHttpStatus: null,
    callbackErrorType: null,
    callbackErrorMessage: null,
    processedCount: 0,
    ingestedCount: 0,
    duplicateCount: 0,
    exactDuplicateCount: 0,
    skippedSameOriginCount: 0,
    splitCount: 0,
    childCount: 0,
    passedThroughCount: 0,
    rotatedCount: 0,
    normalizedCount: 0,
    ocrCompletedCount: 0,
    extractedCount: 0,
    metadataValidatedCount: 0,
    rightsDeterminedCount: 0,
    underReviewCount: 0,
    versionedCount: 0,
    resolvedCount: 0,
    skippedCount: 0,
    reviewNeededCount: 0,
    failedCount: 0,
    currentPass: 1,
    maxPasses: 1,
    completedPasses: [],
    sourceFolderIds: [],
    collectionName: null,
    collectionNotes: null,
    ...overrides,
  }
}

export function createProcessBatch(overrides: Partial<ProcessBatchStatus> = {}): ProcessBatchStatus {
  return {
    batchId: 'batch-story-1',
    batchName: 'May 2026 Preservation Batch',
    startedBy: 'archivist@example.org',
    createdAt: '2026-05-29T09:30:00.000Z',
    pipelineRequestedStages: processPipelineRequestedStages,
    pipelineConfig: processPipelineConfig,
    ingester: null,
    documentSplitter: null,
    pageRotator: null,
    ocrProcessor: null,
    contentDedup: null,
    metadataExtractor: null,
    metadataValidator: null,
    rightsDeterminator: null,
    ...overrides,
  }
}
