import type { PipelineConfig } from '@lib/pipelineConfig'
import type { ProcessBatchStatus, ProcessStageStatus } from 'types/pipelineContracts'

export const processPipelineConfig: PipelineConfig = {
  profileId: 'custom',
  mode: 'custom',
  executionPlan: [
    { id: 'step-ingester', stepId: 'ingester', service: 'ingester', label: 'Ingest', order: 0, enabled: true },
    {
      id: 'step-splitter',
      stepId: 'document-splitter',
      service: 'document-splitter',
      label: 'Document Splitter',
      order: 1,
      enabled: true,
    },
    {
      id: 'step-rotator',
      stepId: 'page-rotator',
      service: 'page-rotator',
      label: 'Page Rotator',
      order: 2,
      enabled: true,
    },
    {
      id: 'step-ocr',
      stepId: 'ocr-processor',
      service: 'ocr-processor',
      label: 'OCR Processor',
      order: 3,
      enabled: true,
    },
    {
      id: 'step-dedup',
      stepId: 'content-dedup',
      service: 'content-dedup',
      label: 'Content Dedup',
      order: 4,
      enabled: true,
    },
    {
      id: 'step-extractor',
      stepId: 'metadata-extraction',
      service: 'metadata-extraction',
      label: 'Metadata Extractor',
      order: 5,
      enabled: true,
    },
    {
      id: 'step-validator',
      stepId: 'metadata-validation',
      service: 'metadata-validation',
      label: 'Metadata Validator',
      order: 6,
      enabled: true,
    },
    {
      id: 'step-rights',
      stepId: 'rights-determinator',
      service: 'rights-determinator',
      label: 'Rights Determinator',
      order: 7,
      enabled: true,
    },
  ],
}

export function createProcessStage(overrides: Partial<ProcessStageStatus> = {}): ProcessStageStatus {
  return {
    status: 'pending',
    requestId: 'request-1',
    requestedByApp: 'preserv-dashboard',
    initiatedAt: null,
    startedAt: null,
    completedAt: null,
    lastTransitionAt: null,
    error: null,
    callbackDeliveryStatus: null,
    callbackNotifiedAt: null,
    callbackReceivedAt: null,
    callbackHttpStatus: null,
    callbackErrorType: null,
    callbackErrorMessage: null,
    processedCount: 0,
    ingestedCount: 0,
    duplicateCount: 0,
    exactDuplicateCount: 0,
    skippedSameOriginCount: 0,
    splitCount: 0,
    childCount: 0,
    passedThroughCount: 0,
    rotatedCount: 0,
    normalizedCount: 0,
    ocrCompletedCount: 0,
    extractedCount: 0,
    metadataValidatedCount: 0,
    rightsDeterminedCount: 0,
    underReviewCount: 0,
    versionedCount: 0,
    resolvedCount: 0,
    skippedCount: 0,
    reviewNeededCount: 0,
    failedCount: 0,
    currentPass: 1,
    maxPasses: 1,
    completedPasses: [],
    sourceFolderIds: [],
    collectionName: null,
    collectionNotes: null,
    ...overrides,
  }
}

export function createProcessBatch(overrides: Partial<ProcessBatchStatus> = {}): ProcessBatchStatus {
  return {
    batchId: 'batch-story-1',
    batchName: 'May 2026 Preservation Batch',
    startedBy: 'archivist@example.org',
    createdAt: '2026-05-29T09:30:00.000Z',
    pipelineRequestedStages: ['document-splitter', 'page-rotator', 'ocr-processor'],
    pipelineConfig: processPipelineConfig,
    ingester: null,
    documentSplitter: null,
    pageRotator: null,
    ocrProcessor: null,
    contentDedup: null,
    metadataExtractor: null,
    metadataValidator: null,
    rightsDeterminator: null,
    ...overrides,
  }
}
